########################################
# ruby
########################################
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

# endを自動で挿入
[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

# ユーザ定義のテキストオブジェクト
[[plugins]]
repo = 'kana/vim-textobj-user'
on_ft = ['ruby']

# rubyのブロックをテキストオブジェクトとして扱えるようにする
[[plugins]]
repo = 'rhysd/vim-textobj-ruby'
on_ft = ['ruby']

# Rails
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

# UniteのRails拡張
[[plugins]]
repo = 'basyura/unite-rails'
on_ft = ['ruby']
hook_add = '''
    source $HOME/.vim/plugins/unite-rails.vim
'''

########################################
# js
########################################
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

########################################
# go
########################################
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
    source $HOME/.vim/plugins/vim-go.vim
'''

########################################
# terraform
########################################
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']
hook_add = '''
    let g:terraform_fmt_on_save = 1
'''

########################################
# scala
########################################
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']
hook_add = '''
    source $HOME/.vim/plugins/vim-scala.vim
'''
